### ISSUE TITLE
smile

### ISSUE THREAD

**Issue by erelsgl** [mrmarbles/wordsworth#2]
The following sentence:
     "This is a smile :-)"

Causes the following exception:
/home/erelsgl/git/machine-learning-server/node_modules/wordsworth/lib/spell_checker.js:207
  var len = word.length, words = (dict[len].length / len), low = 0,
                                           ^
TypeError: Cannot read property 'length' of undefined
    at SpellChecker.exists (/home/erelsgl/git/machine-learning-server/node_modules/wordsworth/lib/spell_checker.js:207:44)
    at SpellChecker.analyze (/home/erelsgl/git/machine-learning-server/node_modules/wordsworth/lib/spell_checker.js:247:15)

**Comment by erelsgl** [comment]
A similar error occurs when the input string is empty.

**Comment by erelsgl** [comment]
A similar error, when the input string ends with a space, for example, "hi ".

**Comment by mrmarbles** [comment]
Thanks for reporting these Erel.  I'll have some time in the next day or so to address them and will keep you posted.
